version: '3.9'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: shs_mysql
    restart: always
    environment:
     # MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthcare
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shs_network

  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: shs_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - shs_network

  # Spring Boot Backend
  backend:
    build: .
    container_name: shs_backend
    ports:
      - "8080:8081"   # Access via host:8080, app runs on container port 8081
    depends_on:
      - mysql
      - mongodb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/healthcare?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_MONGODB_URI: mongodb://mongo:mongo@mongodb:27017/smart_healthcare?authSource=admin
    networks:
      - shs_network

# Volumes for persistent storage
volumes:
  mysql_data:
  mongo_data:

# Shared network for communication
networks:
  shs_network:
    driver: bridge
